### ISSUE TITLE
ARM64 version

### ISSUE THREAD

**Issue by nift4** [Android-Boot-Manager/Toolkit#1]
This is necessary for arm64 devices as everything is in 64 bit but bins are in 32 bit

**Comment by luka177** [comment]
Butw wount arm32 bin work on 64 ig it will

**Comment by nift4** [comment]
> Butw wount arm32 bin work on 64 ig it will

The binary itself works, but the files to extract are 64 bit and so too much for the 32 bit binary

**Comment by nift4** [comment]
Oh well this was wrong
